ru:
  not_captcha:
    select: "- выбрать -"
    before_you_submit: "Перед отправкой формы:"
    make_image_vertical: "Выставьте эти иконки <b>вертикально</b>"
    move_sliders_or_click: Двигайте ползунки для изменения угла картинок или просто кликайте по картинкам
    reload_images: Обновить картинки
